/**
 * Centralized, env-driven settings for the web dashboard.
 *
 * Values come from Vite env vars (`VITE_*`, see `.env` / `.env.example`) and fall
 * back to sensible defaults so the site still runs with no `.env` present. Only
 * `VITE_`-prefixed vars are exposed to the client bundle by Vite.
 */
const env = import.meta.env;

const clean = (value: string | undefined): string => (value ?? "").trim();

export const config = {
  /** App version shown in the hero "New v…" tag. */
  version: clean(env.VITE_APP_VERSION) || "2.0",
  /** Public GitHub repository (navbar + hero "GitHub" buttons). */
  githubUrl: clean(env.VITE_GITHUB_URL) || "https://github.com/MichaelLeHoang/LegitMate",
  /**
   * Chrome Web Store listing for the extension. Empty until published — while
   * empty, "Add to Chrome" opens the install modal (download the .zip + load
   * unpacked). Once set, the buttons open the store listing instead.
   */
  chromeStoreUrl: clean(env.VITE_CHROME_STORE_URL),
  /**
   * Download URL for the packaged (unpacked) extension zip used during the
   * pre-store phase. Defaults to the file served from the site's `public/`
   * (generated by `make package-extension`); can point at a GitHub release.
   */
  extensionDownloadUrl: clean(env.VITE_EXTENSION_DOWNLOAD_URL) || "/legitmate-extension.zip",
  /** Optional footer legal links. Empty → rendered as inert text. */
  privacyUrl: clean(env.VITE_PRIVACY_URL),
  termsUrl: clean(env.VITE_TERMS_URL)
} as const;

/** True once a Chrome Web Store listing exists — flips "Add to Chrome" from the install modal to the store. */
export const isStoreLive = Boolean(config.chromeStoreUrl);
